services:
  backend:
    build:
      context: ./backend/user-auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: users
      POSTGRES_PASSWORD: Admin@000
      POSTGRES_DB: users
      JWT_SECRET: dIVcQJtrRve_zz4v7xegrA
      JWT_ExpiresIn: 60m
    volumes:
      - ./backend/user-auth:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/user-auth-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/user-auth-frontend:/app
    depends_on:
      - backend

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: Admin@000
      POSTGRES_DB: users
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fotrosi@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: Admin@007
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: