services:
  backend:
    build:
      context: ./backend/user-auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass123"
      POSTGRES_DB: "postgres"
    volumes:
      - ./backend/user-auth:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/user-auth-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/user-auth-frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass123"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: